#!/bin/sh

xmodmap "/home/gh/.Xmodmap"
/usr/bin/synclient TapButton1=1
/usr/bin/setxkbmap -layout "us,bg" -option "grp:alt_shift_toggle"
/usr/bin/fbsetbg ~/wallpaper/wallpaper
/usr/bin/amixer sset Headphone,0 100%
/usr/bin/amixer sset Speaker,0 100%
/usr/bin/amixer sset PCM,0 100%
export BROWSER=/usr/bin/chromium

xscreensaver &
parcellite &
dropbox start -i
kmix &
wicd-client &
sudo nm-applet &
conky &
#eval "$(gpg-agent --daemon)" &

exec fluxbox
# exec fluxbox -log "/home/gh/.fluxbox/log"
